name: Deploy front staging
on:
  push:
    branches:
      - dev
jobs:
  Deploy-Front-Staging:
    runs-on: ubuntu-22.04
    steps:
      - name: SSH remote commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.STAGING_SERVER_ID_RSA }}
          script: |
            cd ${{ vars.STAGING_PROJECT_DIRECTORY }}
            git pull
            docker-compose up --build -d
      - run: apt update && apt install curl -y
      - run: while  ! curl -sI $STAGING_FRONT_BASE_URL | grep 401; do sleep 1; done && echo "server is running"
